import type { Activity } from "@/types";

export const activities: Activity[] = [
  {
    title: "Validar estabilidade do WebSocket",
    project: "Workshop Automation",
    provider: "Mobato",
    owner: "Victor Fazekas",
    initials: "VF",
    priority: "HIGH",
    status: "IN_PROGRESS",
    due: "Hoje",
  },
  {
    title: "Atualizar documentação da API",
    project: "Repair Order Hub",
    provider: "Mobato",
    owner: "João Silva",
    initials: "JS",
    priority: "MEDIUM",
    status: "IN_PROGRESS",
    due: "Amanhã",
  },
  {
    title: "Validar ambiente Linx",
    project: "DMS",
    provider: "Linx",
    owner: "Victor Fazekas",
    initials: "VF",
    priority: "HIGH",
    status: "BLOCKED",
    due: "18/09/2026",
  },
  {
    title: "Revisar requisitos OSB",
    project: "Online Service Booking",
    provider: "Dealernet",
    owner: "Maria Souza",
    initials: "MS",
    priority: "MEDIUM",
    status: "IN_PROGRESS",
    due: "20/09/2026",
  },
  {
    title: "Mapear fluxo de cancelamento",
    project: "After Sales Portal",
    provider: "Mobato",
    owner: "João Silva",
    initials: "JS",
    priority: "CRITICAL",
    status: "COMPLETED",
    due: "15/09/2026",
  },
];

